### ISSUE TITLE
How do I set the Callback Route?

### ISSUE THREAD

**Issue by caddac** [verdan/flaskoidc#2]
With my app behind a reverse proxy, and using path base routing upstream I need to add or specify the callback URL. How do I do that?

default: `http://whatever/oidc_callback`
I need: `http://whatever/catalog/oidc_callback`

**Comment by verdan** [comment]
@caddac you should be able to set that with the new version of flaskoidc. 
Can you please give it a try? `0.1.0`

For more info on how to set environment variables for various packages: https://github.com/verdan/flaskoidc/blob/master/README.md

**Comment by verdan** [comment]
should be fixed in the newer version i.e., 0.1.0
