### ISSUE TITLE
Hard-coded version requirements causes tools like poetry to fail

### ISSUE THREAD

**Issue by vilhelmprytz** [verdan/flaskoidc#20]
https://github.com/verdan/flaskoidc/blob/c609373881e16713f5faf3527e7485f38ccaa956/setup.py#L8

In `setup.py`, flaskoidc requires a very specific version of the `requests` package (not the newest version). If you have the newest version of requests installed, flaskoidc won't install (at least not using tools like [poetry](https://python-poetry.org/)).

Would it be possible to change the `setup.py` file to not require versions specifically (or something like `requests>=2.25.1`)?

(this applies to the other requirements as well, but the mismatch I got right now was because of the `requests` package)

**Comment by verdan** [comment]
@vilhelmprytz would you like to open a PR with the change? Feel free to upgrade the version as well.

**Comment by vilhelmprytz** [comment]
@verdan Sorry for the delay, I've submitted a PR replacing `==` with `>=` which I (think) should solve the problem.
